### ISSUE TITLE
Lunch not working

### ISSUE THREAD

**Issue by yehonatan2020** [Evolution-X/manifest#10]
Running lunch for Panther device (Pixel 7) returns an error where 'uname' and 'touch' commands are not found. I tried adding them to build/soong/ui/build/paths/config.go to whitelist them and after lunch giving quite a few more commands not found, lunch eventually completed. However, 'm' command did not work, and using 'make' instead gave back the error where 'uname' and 'touch' commands are not found

20:53:38 Build sandboxing disabled due to nsjail error.
/bin/bash: line 1: uname: command not found
/bin/bash: line 1: touch: command not found
In file included from build/make/core/config.mk:394:
In file included from build/make/core/envsetup.mk:51:
build/make/core/release_config.mk:139: error: release-config failed to run.
20:53:39 dumpvars failed with: exit status 1
20:53:40 Build sandboxing disabled due to nsjail error.
/bin/bash: line 1: uname: command not found
/bin/bash: line 1: touch: command not found
In file included from build/make/core/config.mk:394:
In file included from build/make/core/envsetup.mk:51:
build/make/core/release_config.mk:139: error: release-config failed to run.
20:53:42 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_panther'
** Do you have the right repo manifest?

**Comment by yehonatan2020** [comment]
Hi, 
I have just set up Discord but I'm pretty new to it tbh. How could I connect on discord please?
I'm building on a laptop running Arch Linux. A14 builds just fine. Just A15.
Thanks
Sean
--
Sent from Mail.ru app for Android Monday, 02 December 2024, 09:49am +00:00 from Onelots  ***@***.*** :

**Comment by Oneloutre** [comment]
Okay,

here is our discord link : discord.gg/evolution-x
It will lead you directly in our discord.

Then, kindly ping me using @onelots, I will answer you there :)

besides, it's quite weird if it builds well on A14...
See ya there.

Regards,
