### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [Evolution-X/manifest#224]
Hello! When assembling the firmware for Xiaomi Redmi Note 6 Pro, I get this error. How do I fix it?

[ 99% 580/581] finishing build rules ...
FAILED: 
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1121: error: exiting from previous errors.
01:13:41 ckati failed with: exit status 1

**Comment by Doraemon-Chan** [comment]
Go to Directory hardware/qcom-caf/msm8998/audio and delete audio, then clone hardware/qcom-caf/msm8998/audio then your problem will be solved!

**Comment by HemantSachdeva** [comment]
> Hello! When assembling the firmware for Xiaomi Redmi Note 6 Pro, I get this error. How do I fix it?
> 
> [ 99% 580/581] finishing build rules ... FAILED: hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm64)" You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build. hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm)" You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build. build/make/core/main.mk:1121: error: exiting from previous errors. 01:13:41 ckati failed with: exit status 1

This [patch](https://paste.evolution-x.org/p5A6jS) will help you.

**Comment by Ingvarr71** [comment]
> Go to Directory hardware/qcom-caf/msm8998/audio and delete audio, then clone hardware/qcom-caf/msm8998/audio then your problem will be solved!

Thanks! This helped to solve the problem

**Comment by Ingvarr71** [comment]
> > Hello! When assembling the firmware for Xiaomi Redmi Note 6 Pro, I get this error. How do I fix it?
> > [ 99% 580/581] finishing build rules ... FAILED: hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm64)" You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build. hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm)" You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build. build/make/core/main.mk:1121: error: exiting from previous errors. 01:13:41 ckati failed with: exit status 1
> 
> This [patch](https://paste.evolution-x.org/p5A6jS) will help you.

Thanks! This helped to solve the problem

**Comment by HemantSachdeva** [comment]
Your welcome!

Don't forget to close the issue :)
