### ISSUE TITLE
device_qcom_sepolicy

### ISSUE THREAD

**Issue by boedhack99** [Evolution-X/manifest#234]
Please fix neverallow for generic/private/smart_trace.te

Neverallows:
neverallow check failed at /home/cirrus/roms/Evolution-X-tiramisu/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil:24434 from system/sepolicy/private/perfetto.te:85
  (neverallow base_typeattr_785 perfetto_traces_data_file (dir (ioctl read write create getattr setattr lock relabelfrom relabelto append map unlink link rename execute quotaon mounton audit_access open execmod watch watch_mount watch_sb watch_with_perm watch_reads add_name remove_name reparent search rmdir)))
    <root>
    allow at /home/cirrus/roms/Evolution-X-tiramisu/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil:31199
      (allow vendor_perfetto_dump perfetto_traces_data_file (dir (ioctl read write getattr lock open watch watch_reads add_name remove_name search)))
    <root>
    allow at /home/cirrus/roms/Evolution-X-tiramisu/out/soong/.intermediates/system/sepolicy/plat_policy_for_vendor.cil/android_common/plat_policy_for_vendor.cil:31208
      (allow vendor_perfetto_dump perfetto_traces_data_file (dir (ioctl read write getattr lock open watch watch_reads add_name remove_name search)))

**Comment by Stallix** [comment]
Switched in latest Manifest.
