### ISSUE TITLE
Parallel Space Integration With Evo X Launcher

### ISSUE THREAD

**Issue by GryphonIs** [Evolution-X/manifest#237]
I am switching over to a Google Pixel 7 from a Samsung phone, and I am used to being able to use the secure folder to have second accounts. It would be nice to have something like that with the parallel spaces feature.

Would it be possible to integrate the parallel space apps with the hidden and protected apps section of the Evo X launcher?
At the moment, the parallel apps are not shown in the list. An even better option could be a locked folder that has the parallel apps in it.

**Comment by Stallix** [comment]
Android 14 will be introducing app cloning. No use of re-introducing a redundant feature for Android 13 only to remove it again.

Ref: https://www.xda-developers.com/android-14-app-cloning/
