### ISSUE TITLE
external_faceunlock not found

### ISSUE THREAD

**Issue by TejasKamat** [Evolution-X/manifest#238]
external_faceunlock:
remote: 404 page not found
fatal: repository 'https://gitlab.pixelexperience.org/android/external_faceunlock/' not found
error: Cannot fetch external_faceunlock from https://gitlab.pixelexperience.org/android/external_faceunlock
Fetching: 100% (1/1), done in 7.124s
Checking out: 100% (1172/1172), done in 7.233s

error: Unable to fully sync the tree.
error: Downloading network changes failed.
Try re-running with "-j1 --fail-fast" to exit at the first error.

**Comment by Stallix** [comment]
Syncs fine here. Skill issue.
