### ISSUE TITLE
Evolution X for Pixel 3 build

### ISSUE THREAD

**Issue by alex1491163117** [Evolution-X/manifest#239]
How to build Pixel3 android13? I encountered the following error. thanks

lunch evolution_blueline-userdebug

In file included from build/make/core/config.mk:352:
In file included from build/make/core/envsetup.mk:352:
build/make/core/product_config.mk:228: error: Can not locate config makefile for product "evolution_blueline".
21:15:18 dumpvars failed with: exit status 1
Device blueline not found. Attempting to retrieve device repository from Evolution-X-Devices Github (http://github.com/Evolution-X-Devices).
Found repository: device_google_blueline
Checking branch info
Calculated revision: tiramisu
already exists: device/google/blueline
Syncing repository to retrieve project.

... A new version of repo (2.32) is available.
... You should upgrade soon:
    cp /mnt/data2/source/Evolution-X/rom/.repo/repo/repo /home/bks/bin/repo

Fetching: 100% (1/1), done in 2.037s
repo sync has finished successfully.
Repository synced!
Looking for dependencies
Dependency already present in manifest: device_google_crosshatch => device/google/crosshatch
Done
In file included from build/make/core/config.mk:352:
In file included from build/make/core/envsetup.mk:352:
build/make/core/product_config.mk:228: error: Can not locate config makefile for product "evolution_blueline".

**Comment by Stallix** [comment]
Not the place to ask how to build. Contact us in https://t.me/EvolutionXBuilders.
