### ISSUE TITLE
clang-r416183b It's missing from the source

### ISSUE THREAD

**Issue by HeroRickyGAMES** [Evolution-X/manifest#240]
I don't know why but every time I do a new build for Poco F1 this error happens, in the last update (49) this did not happen, I had to get it from another source and clone it in the correct directory. At least it fixed the bug because now it's building normally, but I think this would be interesting to put and correct to avoid this error.

**Comment by Stallix** [comment]
https://github.com/Evolution-X/manifest/blob/a1639f19d47966edd80117ac959fa64d806f9f3b/lineage.xml#L12

It's literally being tracked here.
