### ISSUE TITLE
realmeparts on latest manifests qupr2

### ISSUE THREAD

**Issue by Jordibgzashtita** [Evolution-X/manifest#254]
```
symbol:   class R
  location: package com.android.settingslib.widget
device/realme/RMX1971/RealmeParts/src/org/device/RealmeParts/Touch/ScreenOffGestureSettings.java:22: error: cannot find symbol
import com.android.settingslib.widget.R;
```

https://jenkins.bgzashtita.es/job/cherish/3/console

Here is device tree: https://github.com/kaderbava/device_realme_RMX1971/tree/14-evo

remove dynamic partitions we want use full gms without this we can't compile.

**Comment by ij-israfil** [comment]
https://github.com/ij-israfil/device_realme_RMX1901/commit/b71c48ea6e1c555145e5e02d854f39b71b984d5f
